const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const refs={dart:'https://home.dartmouth.edu/about/artificial-intelligence-ai-coined-dartmouth',history:'https://www.ibm.com/think/topics/history-of-artificial-intelligence',blue:'https://www.ibm.com/history/deep-blue',alex:'https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks',go:'https://deepmind.google/research/alphago/',attention:'https://arxiv.org/abs/1706.03762',ng:'https://www.deeplearning.ai/the-batch/how-ai-will-create-jobs',gates:'https://www.gatesnotes.com/a-turbulent-ai-era-and-critical-choices-to-make',career:'https://www.etnews.com/20250113000235',career2:'https://www.thevaluenews.co.kr/news/180842',linkedin:'https://www.linkedin.com/in/jungshik-jang-2878106/',chat:'https://openai.com/index/chatgpt/',agent:'https://www.anthropic.com/engineering/building-effective-agents'};
const source=(key,title)=>`<div class="source">읽을거리 · <a href="${refs[key]}" target="_blank" rel="noopener noreferrer">${title} ↗</a></div>`;
const lab=(title,body)=>`<div class="panel"><div class="lab-label">${title}</div>${body}</div>`;
const split=(text,right)=>`<div class="split"><div>${text}</div>${right}</div>`;
const sections=[];
function add(id,kicker,time,title,body,note){sections.push({id,kicker,time,title,body,note});}
add('intro','프롤로그','00–03분 · 3분','',`<div class="eyebrow">HANSOL HIGH SCHOOL <span>진로 × 기술 × 삶 · 100분</span></div><h1>어쩌다 <em>AI</em></h1><p class="subtitle">시골 무지랭이가<br>AI 전문가로 불리기까지.</p><p class="muted">장정식 · 소프트웨어 엔지니어</p><div class="hero-bottom">아직 정해지지 않은 당신의 다음을 위해 &nbsp; / &nbsp; SCROLL TO EXPLORE ↓</div>`,`첫 30초는 제목만 보여주세요. “시골 무지랭이”는 자신의 출발을 돌아보는 표현이지 지역이나 사람의 가능성을 평가하는 말이 아님을 덧붙이세요. 손들기: AI를 써 본 사람? AI 때문에 진로가 걱정되는 사람? 목표는 AI를 겁내거나 맹신하지 않고 설명하고 사용하며 자기 선택을 만드는 것입니다.`);
add('opening','오늘의 질문','03–06분 · 3분','꿈이 아직 없으면,<br>늦은 걸까요?',`<p class="lead">지금 나에게 더 가까운 말을 골라보세요.</p><div class="row" id="opening-choices"><button data-thought="정해진 꿈이 있다면, 그 직업이 매일 하는 일을 하나 찾아봅시다.">하고 싶은 일이 있어요</button><button data-thought="관심이 여러 개라면, 두 가지를 연결하는 작은 실험을 해봅시다.">좋아하는 건 많아요</button><button data-thought="아직 모른다면, 이번 주에 관찰할 불편 하나부터 찾아봅시다.">아직 잘 모르겠어요</button></div><div class="output" id="opening-result" aria-live="polite">어느 쪽이든 오늘의 출발점이 됩니다.</div><div class="agenda"><div><b>18′</b>나의 경로</div><div><b>50′</b>AI 역사 실험실</div><div><b>5′</b>쉬어가기</div><div><b>13′</b>미래의 일</div><div><b>9′</b>나의 다음</div><div><b>5′</b>질문</div></div>`,`30초 개인 선택 → 옆 사람과 1분 이야기 → 두 명의 응답을 들어보세요. 선택은 이 화면에서만 바뀌며 학급 투표나 집계가 아닙니다. “오늘은 평생의 직업을 정하는 시간이 아니라 다음 실험을 고르는 시간입니다.”`);
add('story','01 / 나의 경로','06–12분 · 6분','직함보다,<br>풀어온 문제들.',`<p class="lead">게임, 검색과 플랫폼, 광고 기술, 그리고 여행.<br>분야는 바뀌어도 소프트웨어로 문제를 푸는 경험은 이어졌습니다.</p><div class="timeline"><article><strong>넥슨</strong><p>게임과 서비스 개발</p></article><article><strong>Google</strong><p>검색·안드로이드 TV 등 제품과 플랫폼</p></article><article><strong>Moloco</strong><p>광고 기술 영역의 개발 경험</p></article><article><strong>야놀자 · NEXT</strong><p>데이터 플랫폼·AI/ML·여행 서비스</p></article></div><p class="small">공개 보도와 기존 공유 이력에 기반한 경력 요약. 현직을 단정하는 소개가 아닙니다.</p>${source('career2','2024.01.22 경력 보도')}${source('career','2025.01.13 클라우드 CTO 선임 보도')}`,`회사 이름은 짧게, 실제 했던 일은 학생 언어로 설명하세요. “검색은 필요한 것을 찾게 하는 일, 광고는 맞는 대상을 연결하는 일, 여행 기술은 복잡한 과정을 줄이는 일.” 이 경력 순서만으로 입사 동기나 감정을 추정하지 않았습니다. 실제 전환 계기는 다음 장에서 본인 경험으로 이야기해주세요.`);
add('turning','01 / 선택의 장면','12–17분 · 5분','이력서에 없는<br>세 장면.',`<div class="timeline" style="grid-template-columns:repeat(3,1fr)"><article><strong>처음 빠져든 것</strong><p>시간 가는 줄 모르고<br>해본 일은 무엇이었나?</p></article><article><strong>막혔던 순간</strong><p>뜻대로 되지 않았을 때<br>무엇을 바꿨나?</p></article><article><strong>다시 고른 방향</strong><p>그 선택에서 얻고,<br>포기한 것은 무엇인가?</p></article></div><p class="quote">진로는 한 번의 정답보다<br><em>선택하고 돌아보는 과정.</em></p>`,`개인 일화는 아직 작성하지 않았습니다. 준비할 실제 이야기 3개: ① 고향·학창 시절과 컴퓨터를 처음 만난 장면 90초 ② 실패 또는 막막했던 전환 90초 ③ 다음 일을 고른 이유와 삶의 기준 90초. 각 장면을 “상황 → 선택 → 대가 → 배운 점”으로 말하세요. 현재 확보한 공개 자료로 성장 환경이나 실패 경험은 검증할 수 없습니다. 학생에게는 실력뿐 아니라 주변 사람·기회·환경의 도움도 함께 들려주세요.`);
add('compass','01 / 진로의 나침반','17–20분 · 3분','평생의 직업 대신,<br>다음 실험 하나.',split(`<p class="lead">흥미, 실력, 타인의 필요.<br>셋이 만나는 지점은 해보면서 찾을 수 있습니다.</p><p class="muted">직업이 삶의 전부는 아닙니다.<br>건강, 관계, 시간도 선택의 기준입니다.</p>`,lab('YOUR NEXT EXPERIMENT',`<label>관심 있는 것<input id="interest" type="text" placeholder="예: 음악, 게임, 운동" maxlength="70"></label><label>주변에서 발견한 불편<input id="problem" type="text" placeholder="예: 동아리 공연 일정을 자꾸 놓친다" maxlength="140"></label><button id="experiment" style="margin-top:16px">작은 실험으로 바꾸기</button><div id="experiment-result" class="output" aria-live="polite">관심과 불편을 하나씩 적어보세요.</div>`)),`입력은 서버로 보내지 않습니다. 결과는 입력 문장을 결합한 활동 안내이며 AI 생성이 아닙니다. 1분 작성 → 1분 옆 사람에게 설명 → 1분 피드백. “유명한 회사”보다 “어떤 문제를, 누구와, 어떤 생활 속에서 풀고 싶은가?”로 질문을 바꾸세요.`);
add('rules','02 / AI의 시간 · 1950–1980s','20–25분 · 5분','사람의 규칙을<br>기계에 적어 넣다.',split(`<p class="lead">1950년 튜링의 질문.<br>1956년 다트머스에서 연구 분야가 모이다.</p><p>초기 AI의 한 흐름은 지식과 규칙을 사람이 쓰는 방식이었습니다. 전문가 시스템은 이런 접근을 특정 영역에 적용했습니다.</p><p class="small">AI: 인식·예측·생성·의사결정 등 지능과 관련된 과제를 수행하는 시스템을 연구하는 넓은 분야.</p>${source('dart','Dartmouth · AI의 출발')}`,lab('LAB 01 / 규칙 기반 분류',`<p>규칙: “무료”가 포함된 메시지를 광고로 분류한다.</p><label>검사할 메시지<input id="rule-input" type="text" value="오늘 무료 급식 신청하세요" maxlength="150"></label><label style="margin-top:14px"><input type="checkbox" id="rule-extra">“급식”이 있으면 예외로 처리</label><div id="rule-result" class="output" aria-live="polite"></div><p class="small">“공짜 쿠폰 받으세요”도 넣어보세요.<br>규칙을 늘리면 모든 예외를 해결할 수 있을까요?</p>`)),`1분 역사 → 2분 예제 → 2분 토론. 무료 급식은 오탐, 공짜 쿠폰은 놓치는 사례입니다. 이 실험은 학습하지 않습니다. Turing의 대화 중심 평가와 실제 이해·의식은 같은 주장이 아님을 짚어주세요. 규칙 기반과 신경망 연구는 시간상 겹치며 한 시대가 완전히 교체되는 것은 아닙니다.`);
add('learning','02 / AI의 시간 · 1958 → 머신러닝','25–31분 · 6분','정답을 쓰는 대신,<br>예시에서 배우게 하다.',split(`<p class="lead">입력과 정답을 보여주고,<br>틀린 만큼 기준을 조정합니다.</p><p>퍼셉트론은 가중합과 문턱값으로 분류하는 초기 신경망 모델입니다. 머신러닝은 데이터에서 규칙을 학습하는 접근입니다.</p><p class="small">실험: 가상의 과일 무게 하나로 두 종류를 분류합니다. 실제 과일 판별 모델이 아닙니다.</p>${source('history','IBM · AI 역사')}`,lab('LAB 02 / 데이터에 맞춰 경계 학습',`<svg id="learn-plot" class="plot" viewBox="0 0 500 170" role="img" aria-label="가상 과일 데이터와 분류 경계"></svg><label>분류 경계 <output id="threshold-text"></output><input id="threshold" type="range" min="20" max="90" value="30"></label><div class="row"><button id="train">학습 한 단계</button><button id="bias">편향된 데이터 보기</button><button id="learn-reset">초기화</button></div><div id="learn-result" class="output" aria-live="polite"></div><p class="small">원: A / 마름모: B · 아래쪽 표시: 새 시험 데이터<br>훈련에 없던 예시는 별도로 평가해야 합니다.</p>`)),`2분 설명 → 학생이 경계 조절 1분 → 학습 반복 1분 → 편향된 데이터와 시험 성능 비교 2분. 이 구현은 유한한 경계 후보의 분류 오류를 비교해 더 나은 방향으로 이동하는 간단한 학습입니다. 퍼셉트론 업데이트나 경사하강법을 그대로 구현한 것은 아닙니다. 입력을 바꿔도 예측이 완벽하지 않은 이유를 묻고, 훈련 정확도와 일반화를 구분하세요.`);
add('winter','02 / AI의 시간 · 겨울과 탐색','31–35분 · 4분','똑똑해 보여도,<br>세상은 더 복잡했다.',split(`<p class="lead">1970~90년대에는 과도한 기대와 성능·비용의 간극으로 투자와 관심이 식는 시기도 있었습니다.</p><p>1997년 Deep Blue는 체스 세계 챔피언과의 경기에서 승리했습니다. 핵심에는 빠른 탐색과 평가가 있었습니다.</p>${source('blue','IBM · Deep Blue')}`,lab('LAB 03 / 경우의 수가 폭발한다',`<label>한 번에 가능한 선택 수 <output id="branch-out"></output><input type="range" id="branch" min="2" max="30" value="10"></label><label>몇 수 앞까지 볼까? <output id="depth-out"></output><input type="range" id="depth" min="1" max="10" value="4"></label><div id="search-result" class="output" aria-live="polite"></div><p class="small">단순한 완전 탐색 나무의 말단 수 bᵈ입니다.<br>Deep Blue의 실제 계산량이나 성능 추정은 아닙니다. 유망한 선택부터 보는 방법이 필요해집니다.</p>`)),`학생에게 깊이를 4에서 8로 바꾸면 두 배가 되는지 물은 뒤 조작하세요. 실제 체스는 가지치기와 평가 함수를 씁니다. AI의 겨울은 모든 연구가 멈춘 사건이 아니라 분야별 기대·자금·성능의 엇갈림입니다. 진로 연결: 관심이 줄어든 때에도 남는 문제와 기본기를 볼 수 있을까요?`);
add('deep','02 / CNN · 1/4 · 2012','35–41분 · 6분','픽셀에서 시작하는 CNN.',split(`<p class="lead">CNN(합성곱 신경망)은 작은 영역의 패턴을 찾고, 여러 층에서 조합합니다.</p><p>2012년 AlexNet은 ImageNet 대회에서 이미지 분류의 큰 진전을 보여줬습니다. 데이터, GPU, 학습 방법이 함께 작용했습니다.</p><p class="small">AI ⊃ 머신러닝 ⊃ 딥러닝.<br>뇌를 그대로 복제한 것이라고 이해하면 곤란합니다.</p>${source('alex','Krizhevsky 외 · AlexNet 논문')}`,lab('LAB 04 / 작은 필터로 패턴 찾기',`<div class="row spread"><span>픽셀을 눌러 모양을 바꿔보세요.</span><select id="filter" aria-label="특징 필터" style="width:auto"><option value="edge">세로 경계</option><option value="horizontal">가로 경계</option></select></div><div class="gridbox"><div id="pixels" class="grid" style="grid-template-columns:repeat(6,1fr)"></div></div><div class="row"><button id="pixel-reset">기본 패턴</button><button id="pixel-clear">지우기</button></div><div id="filter-result" class="output" aria-live="polite"></div><p class="small">반응의 절댓값을 합계·최댓값으로 요약한 실험입니다. 다음 장에서는 필터의 숫자와 위치별 계산을 직접 봅니다. 학습된 AlexNet은 아닙니다.</p>`)),`1분 역사 → 1분 픽셀 설명 → 2분 선을 그려 필터 비교 → 2분 토론. 작은 창에서 숫자를 곱하고 더하면 경계 반응을 얻습니다. 실제 CNN은 이 필터 값도 학습하며 여러 층의 결과로 분류합니다. 실험은 경계 응답만 보여주므로 “고양이를 인식했다” 같은 해석은 하지 마세요.`);
add('reinforcement','02 / AI의 시간 · 2016','41–47분 · 6분','답안지 없이,<br>결과에서 배우다.',split(`<p class="lead">행동 → 보상 → 다음 선택.<br>강화학습은 경험에서 전략을 개선합니다.</p><p>AlphaGo는 신경망, 탐색, 강화학습을 결합해 이세돌 9단과의 대결에서 승리했습니다. 초기 AlphaGo는 인간의 기보에서도 배웠습니다.</p>${source('go','Google DeepMind · AlphaGo')}`,lab('LAB 05 / 보상을 찾아가는 에이전트',`<div id="rl-grid" class="grid gridbox" style="grid-template-columns:repeat(4,1fr)"></div><div class="row"><button id="rl-train">200번 연습</button><button id="rl-run">배운 경로 보기</button><button id="rl-reset">초기화</button></div><div class="output" id="rl-result" aria-live="polite">시작 S → 목표 G · ×는 피할 곳</div><p class="small">실제 Q-learning을 쓰는 작은 격자입니다.<br>이동 −1 / 목표 +20 / 함정 −15. AlphaGo 자체의 재현은 아닙니다.</p>`)),`1분 역사 → 1분 보상 설명 → 학습 전 경로 보기 1분 → 200번 학습 후 비교 1분 → 2분 토론. 연습 중에는 일부러 탐험하고, 경로 시연에서는 배운 값을 이용합니다. 목표가 조회 수뿐인 추천 AI는 어떤 행동을 배울까요? 잘못 정한 보상이 원치 않는 결과를 낼 수 있다는 연결을 만드세요.`);
add('attention','02 / AI의 시간 · 2017','47–53분 · 6분','한 단어를 읽을 때,<br>다른 단어를 참고하다.',split(`<p class="lead">“나는 은행에서 사과를 먹었다.”<br>은행은 금융기관일까, 나무일까?</p><p>Transformer의 attention은 문맥 속 다른 토큰의 정보를 가중해 결합합니다. 토큰은 글을 나눈 조각으로, 단어와 항상 같지는 않습니다.</p>${source('attention','Vaswani 외 · Attention Is All You Need')}`,lab('LAB 06 / 문맥이 해석을 바꾸는 순간',`<label>문장 선택<select id="context"><option value="money">나는 은행에서 돈을 찾았다</option><option value="tree">나는 은행나무 아래에서 쉬었다</option></select></label><div id="token-list" class="tokens"></div><div id="attention-bars" class="bars"></div><p class="small">단어를 누르면 연결 강도를 봅니다. 가중치는 설명을 위해 정한 값이며 실제 모델의 attention이 아닙니다. Attention만으로 인간 같은 이해나 의식을 입증하지 않습니다.</p>`)),`2분 문맥 설명 → 2분 단어 클릭·문장 변경 → 2분 다음 토큰으로 연결. 실제 self-attention은 입력에서 query/key/value를 만들고 유사도와 softmax로 가중치를 구합니다. 학생에게는 참고할 문맥의 비중을 정하는 방식까지만 설명해도 충분합니다. 시각화 수치는 수작업 예시임을 말해주세요.`);
add('generation','02 / AI의 시간 · 2022','53–59분 · 6분','다음 조각을 예측하면,<br>문장이 자란다.',split(`<p class="lead">대규모 언어 모델은 문맥을 바탕으로<br>다음 토큰의 확률을 계산합니다.</p><p>2022년 ChatGPT는 대화형 생성 AI의 대중화를 이끌었습니다. 사전학습 외에도 지시 수행과 선호를 반영하는 추가 학습 등이 사용됩니다.</p><p class="small">그럴듯한 문장과 사실 확인은 별개의 문제입니다.</p>${source('chat','OpenAI · Introducing ChatGPT')}`,lab('LAB 07 / 다음 단어 뽑기',`<p class="subtitle">오늘 나는 <span id="sample-word" class="teal">___</span></p><label>다양성 · temperature <output id="temp-out"></output><input id="temp" type="range" min="0.2" max="2" step="0.1" value="1"></label><div id="prob-bars" class="bars"></div><button id="sample" style="margin-top:20px">다음 단어 뽑기</button><p class="small" style="margin-top:16px">미리 정한 네 단어의 확률을 온도로 조정하고 무작위 추출합니다. 실제 LLM이 아닙니다. 낮은 온도도 사실성을 보장하지 않습니다.</p>`)),`1분 대중화 → 2분 확률·샘플링 → 1분 온도 변경 → 2분 검증 질문. 창의적 글쓰기와 날짜·출처 확인에 같은 기준을 쓰면 될까요? 이 실험에서 수치가 바뀌는 것은 softmax(log(p)/T)이며 모델 지식이 늘어나는 것은 아닙니다. 토큰 예측이라는 학습 과제만으로 모델의 모든 내부 능력을 설명했다고 단정하지 마세요.`);
add('agents','02 / AI의 시간 · 2024–2026','59–65분 · 6분','말하는 AI에서,<br>도구를 쓰는 AI로.',split(`<p class="lead">텍스트·이미지·음성을 다루는 모델,<br>그리고 여러 단계로 일하는 에이전트.</p><p>에이전트는 목표를 위해 도구를 사용하고 결과를 확인하며 다음 행동을 선택합니다. 능력은 모델·도구·과제에 따라 다릅니다.</p>${source('agent','Anthropic · Building effective agents')}`,lab('LAB 08 / 여행 계획의 검증 루프',`<p>목표: 토요일, 예산 5만 원 안에서 당일 여행</p><label><input type="checkbox" id="agent-error" checked>검색 도구가 오래된 가격을 반환</label><div class="row" style="margin-top:16px"><button id="agent-step">다음 단계</button><button id="agent-reset">다시 시작</button></div><div id="agent-result" class="output" aria-live="polite">목표를 읽고 조건을 정리할 준비가 됐습니다.</div><p class="small">가상 도구 응답을 쓰는 단계별 시뮬레이션입니다. 검색·예약·결제는 실행하지 않습니다.</p>`)),`단계를 누르며 계획 → 도구 사용 → 검사 → 재시도 → 사람 승인 순서를 보세요. 2분 시연, 2분 오래된 가격을 끄고 비교, 2분 책임 토론. 멀티모달은 입력·출력 종류, 에이전트는 행동 흐름의 구분입니다. 청소년 활동에서는 개인정보를 입력하지 않고, 실제 지출이나 외부 전송 전에는 사람이 확인하는 이유를 설명하세요.`);
add('pause','쉬어가기','65–70분 · 5분','잠깐, 화면 밖으로.',`<div class="break"><p class="lead" style="margin:0 auto 20px">눈을 쉬고, 몸을 펴고, 물 한 모금.</p><div id="break-clock" class="big-number">05:00</div><div class="row" style="margin-top:28px"><button id="break-start">타이머 시작</button><button id="break-reset">5분으로 초기화</button></div></div>`,`5분 휴식. 돌아온 뒤 “오늘 본 AI는 규칙을 따르는가, 예시에서 배우는가, 도구를 쓰는가?”를 한 문장씩 회상시켜주세요. 시간은 실제 경과 시간을 기준으로 계산합니다.`);
add('future','03 / 너의 다음 · 서로 다른 전망','70–76분 · 6분','미래는 아직,<br>하나의 답이 아닙니다.',`<div class="split"><article><div class="eyebrow">ANDREW NG <span>2026.02.20</span></div><h3>창작과 실행의 문턱이 낮아지면<br>새로운 일이 생길 수 있다.</h3><p class="muted">AI가 사람의 창의성을 확대해 새로운 의미 있는 일을 만들 것이라는 낙관적 전망.</p>${source('ng','How AI Will Create Jobs')}</article><article><div class="eyebrow">BILL GATES <span>2026년 글 · 9월 7일 확인</span></div><h3>일자리의 손실과 전환에<br>사회가 준비해야 한다.</h3><p class="muted">큰 고용 충격을 우려하며, 인간에게 남길 역할과 사회적 대응을 논의.</p>${source('gates','The turbulent AI era is here')}</article></div><p class="small" style="margin-top:30px">두 사람의 주장 요약입니다. 확정된 미래나 직업별 생존 예측표가 아닙니다.</p><div class="row"><button data-future="새로운 수요가 생긴다면, 그것을 발견하는 사람에게 기회가 생깁니다.">새로운 일이 더 생길 것 같다</button><button data-future="전환 비용이 크다면, 교육·보호·분배에 관한 공동의 선택이 필요합니다.">일자리 감소가 더 걱정된다</button><button data-future="둘은 동시에 일어날 수 있습니다. 분야와 사람에 따라 영향이 다를 수 있습니다.">둘 다 일어날 것 같다</button></div><div id="future-result" class="output" aria-live="polite">내 판단을 바꿀 증거는 무엇일까요?</div>`,`각 전망 1분씩 → 2분 짝 토론 → 2분 발표. 원문을 한국어로 요약한 것이며 직접 인용이 아닙니다. Gates 글의 페이지 날짜 표기가 불안정해 연도와 확인일을 표기했습니다. “누가 더 유명한가”가 아니라 새 수요, 도입 속도, 비용, 책임, 정책이라는 가정을 비교하세요. 두 전망을 평균내서 정답이라고 말하지 않습니다.`);
add('jobs','03 / 직업을 분해해보기','76–81분 · 5분','직업 이름보다,<br>그 안의 일을 보세요.',split(`<p class="lead">“교사가 사라질까?”에서<br>“교사의 어떤 일이 달라질까?”로.</p><label>살펴볼 직업<select id="job"><option value="teacher">교사</option><option value="developer">개발자</option><option value="designer">디자이너</option><option value="nurse">간호사</option></select></label><p class="small">분류는 토론용 판단입니다. 노동시장 통계나 자동화 확률이 아닙니다. 마지막 책임과 현장 조건을 함께 생각하세요.</p>`,lab('WORKSHOP / 업무별 역할 나누기',`<div id="job-tasks" class="tasks"></div><div id="job-result" class="output" aria-live="polite"></div>`)),`한 직업을 골라 1분 동안 업무를 읽고, 2분 동안 AI 초안·사람과 협업·사람 중심으로 분류합니다. 2분 발표에서 같은 일을 다르게 분류한 이유를 물으세요. 직업마다 가능한 자동화가 다르며 “사람 중심”도 영원히 기술적으로 불가능하다는 뜻은 아닙니다. 간호 예시는 개인 의료 조언이 아닌 역할 토론입니다.`);
add('scenarios','03 / 살아갈 세상의 모습','81–85분 · 4분','같은 기술,<br>다른 삶의 모습.',`<p class="lead">기술의 성능만으로 결과가 정해지지는 않습니다.</p><div class="timeline" style="grid-template-columns:repeat(3,1fr)"><article><strong>작은 팀의 큰 작업</strong><p>혼자서 초안을 만들고 시제품을 시험하는 비용이 낮아진다면?</p><p class="small">새 문제를 찾는 힘 · 사용자 이해</p></article><article><strong>첫 경험의 변화</strong><p>초급 업무가 줄면, 신입은 어디에서 숙련을 쌓을까?</p><p class="small">학교 프로젝트 · 멘토링 · 현장 경험</p></article><article><strong>남겨둘 인간의 역할</strong><p>효율이 높아도 사람에게 맡기고 싶은 일은 무엇일까?</p><p class="small">신뢰 · 관계 · 책임 · 사회적 합의</p></article></div><p class="small">앞선 전망을 바탕으로 만든 수업용 시나리오입니다. 실현 시점과 규모는 불확실합니다.</p>`,`각 시나리오 40초 소개 후 하나를 골라 2분 토론하세요. “모두 코딩을 해야 한다” 대신 “자신의 분야에서 문제를 이해하고 AI의 결과를 평가해야 한다”를 제안합니다. 분배와 기회의 문제를 개인 노력 부족으로 환원하지 마세요.`);
add('skills','04 / 나의 다음','85–90분 · 5분','AI에게 맡길수록,<br>내가 알아야 할 것.',`<div class="statement"><span class="teal">01 &nbsp;</span> 질문하기 — 누구의 어떤 문제를 풀고 있지?</div><div class="statement"><span class="teal">02 &nbsp;</span> 확인하기 — 출처와 반례가 있나? 직접 시험했나?</div><div class="statement"><span class="teal">03 &nbsp;</span> 설명하기 — AI 없이도 내 말로 말할 수 있나?</div><div class="statement"><span class="teal">04 &nbsp;</span> 함께하기 — 누구의 동의와 도움이 필요한가?</div><div class="statement"><span class="teal">05 &nbsp;</span> 기본기 쌓기 — 읽기·쓰기·수학·분야 지식이 판단을 돕는다.</div><p class="small" style="margin-top:22px">학습 방법 제안: 먼저 혼자 시도 → AI에게 힌트 요청 → 답을 가리고 설명 → 새로운 문제로 확인.</p>`,`두 사람의 미래 예측에서 분리한 강의의 교육적 제안입니다. 2분 설명 후 학생에게 “AI가 써준 수행평가를 그대로 내면 무엇을 잃는가?”를 묻고 2분 토론, 1분 정리하세요. 학교의 과제 규칙을 따르고 AI 사용 범위를 밝히며, 실명·연락처·친구 사진은 입력하지 않는 구체적 습관을 안내하세요.`);
add('nextweek','04 / 7일짜리 실험','90–95분 · 5분','다음 주의 나에게<br>작은 증거를 남기기.',split(`<p class="lead">거창한 창업도, 완벽한 진로도 필요 없습니다. 누군가의 작은 불편 하나를 줄여보세요.</p><div class="stack"><span>1–2일 · 한 사람에게 물어보기</span><span>3–4일 · AI와 작은 초안 만들기</span><span>5–6일 · 직접 써보고 틀린 곳 찾기</span><span>7일 · 바뀐 점과 배운 점 한 장으로 남기기</span></div>`,lab('MY FIRST STEP',`<label>내가 해볼 일<textarea id="commitment" placeholder="예: 동아리 공지 3개로 일정표를 만들고, 친구 한 명에게 정확한지 확인받겠다." maxlength="600"></textarea></label><label>성공했다고 판단할 작은 증거<input id="evidence" type="text" placeholder="예: 날짜 오류 0개, 친구가 일정 하나를 쉽게 찾음" maxlength="200"></label><button id="commit-btn" style="margin-top:16px">내 다짐 펼치기</button><div id="commit-result" class="output" aria-live="polite"></div><p class="small">이 화면에만 표시됩니다. 새로고침하면 사라지니 필요하면 화면을 캡처하세요.</p>`)),`2분 개인 작성 → 2분 짝에게 말하기 → 1분 발표. AI 접근이 어려운 학생은 종이 초안으로 동일한 실험을 해도 됩니다. 성공을 다운로드 수나 수익으로 정할 필요는 없습니다. “내가 틀린 것을 하나 찾았다”도 좋은 증거입니다.`);
add('closing','에필로그','95–100분 · 5분','',`<p class="quote">아직 무엇이 될지 몰라도,<br><em>무엇을 궁금해할지는</em><br>오늘 고를 수 있습니다.</p><div class="row" style="margin-top:28px"><span class="pill">Q & A</span><span class="muted">AI가 궁금한가요? &nbsp; 일이 궁금한가요? &nbsp; 선택이 궁금한가요?</span></div><p class="hero-bottom">어쩌다 AI &nbsp; / &nbsp; 장정식 × 한솔고등학교</p>`,`마지막 문장은 강의용 제안 문구이며 실제 개인 발언 인용이 아닙니다. 4분 질문, 마지막 1분은 오늘 선택한 작은 실험을 떠올리게 하세요. “무엇이 되면 안전한가요?”에는 보장할 수 없는 직업을 추천하기보다 관심 분야의 실제 업무를 알아보고 작게 실험하자는 방향으로 답해주세요.`);
add('sources','참고 자료','강의 시간 외 · 부록','더 궁금해졌다면.',`<div class="sources">${[['dart','1956 · Dartmouth','AI라는 연구 분야의 출발'],['history','AI 역사 · IBM','튜링, 퍼셉트론, 전문가 시스템과 AI의 겨울'],['blue','1997 · Deep Blue','탐색과 평가로 체스 챔피언에 도전'],['alex','2012 · AlexNet','이미지 분류와 깊은 합성곱 신경망'],['go','2016 · AlphaGo','신경망·탐색·강화학습의 결합'],['attention','2017 · Transformer','Attention Is All You Need 원문'],['chat','2022 · ChatGPT','대화형 AI 공개 소개'],['agent','2024 · Building effective agents','도구를 쓰는 시스템 설계'],['ng','2026.02.20 · Andrew Ng','How AI Will Create Jobs'],['gates','2026 · Bill Gates','The turbulent AI era is here'],['linkedin','장정식 · LinkedIn','요청한 소개 자료 · 본문 접근 제한'],['career','2025.01.13 · 전자신문','야놀자클라우드 CTO 선임 보도']].map(([k,t,d])=>`<div><a href="${refs[k]}" target="_blank" rel="noopener noreferrer">${t} ↗</a><p>${d}</p></div>`).join('')}</div><p class="small">자료 확인: 2026.09.07 · 실험은 브라우저에서 작동합니다. 외부 AI 연결이나 학생 응답 수집은 없습니다.<br>진행 노트: 상단 버튼 · 장 이동: ↑ ↓ 또는 Page Up / Down · 전체 화면: ↗</p>`,`강연 전 개인 이야기 세 장면과 최신 소개를 보완하세요. 강연 날짜가 달라지면 미래 전망 원문을 다시 확인하면 좋습니다. AI 역사는 핵심 개념 중심으로 선별한 것이며 통계학·로봇공학·다양한 연구 흐름 전체를 망라하지 않습니다. 실험 2와 5는 작은 학습 알고리즘, 4와 7은 수학적 원리 실험, 6과 8은 설명용 모델입니다.`);
// Added chapters share the existing lecture's section and lab components.
refs.overfit='https://developers.google.com/machine-learning/crash-course/overfitting/overfitting';
refs.diffusion='https://arxiv.org/abs/2006.11239';refs.rag='https://arxiv.org/abs/2005.11401';
function insertAfter(after,id,kicker,title,body,note){const item={id,kicker,title,body,note,time:''};sections.splice(sections.findIndex(s=>s.id===after)+1,0,item);}
insertAfter('opening','beginning','01 / 작은 시작','큰 세계로 열린,<br>작은 창.',`<figure class="scene"><img src="assets/beginning.png" alt="시골 풍경이 보이는 창가와 오래된 컴퓨터를 표현한 생성 이미지" width="1536" height="1024" fetchpriority="high"><figcaption>강의 주제를 표현한 생성 이미지 · 강연자의 실제 유년 시절 사진이 아닙니다.</figcaption></figure><p class="lead">출발점은 내가 고르지 못해도,<br>궁금한 것을 따라가는 한 걸음은 고를 수 있습니다.</p>`,`이미지를 잠깐 보여준 뒤 실제 컴퓨터와의 첫 만남을 들려주세요. 경험이 아직 확인되지 않아 사건·시기·가족 이야기는 만들지 않았습니다. 개인 노력만으로 모든 환경 차이를 극복할 수 있다는 메시지 대신, 접근 기회와 도움의 중요성도 함께 말해주세요.`);
insertAfter('turning','choices','01 / 선택의 기준','좋은 선택의 기준도<br>사람마다 다릅니다.',split(`<p class="lead">연봉, 배우는 기회, 함께하는 사람,<br>그리고 내 시간. 무엇을 더 중요하게 보나요?</p><p class="small">가상의 두 기회를 비교합니다. 실제 회사 평가나 취업 추천이 아닙니다.</p>`,lab('CAREER EXERCISE / 기준 바꾸기',`<label>배울 기회 중요도 <output id="weight-learn-out"></output><input id="weight-learn" type="range" min="0" max="10" value="5"></label><label>안정성과 생활 중요도 <output id="weight-life-out"></output><input id="weight-life" type="range" min="0" max="10" value="5"></label><p class="small">기회 A: 배움 9 · 생활 4<br>기회 B: 배움 5 · 생활 8 (가상 점수)</p><div id="choice-result" class="output" aria-live="polite"></div>`)),`가중 평균을 움직여 순위가 바뀌는 것을 보세요. 점수가 선택을 대신하지 않습니다. 무엇을 중요하게 여기는지 대화하기 위한 장치입니다. 오늘의 기준이 10년 뒤에도 같아야 할까요?`);
insertAfter('compass','everyday','02 / AI를 알아보는 눈','이미 오늘도,<br>AI를 만났을지 모릅니다.',`<div class="example-grid"><article><span class="example-number">01</span><h3>추천 영상</h3><p>지금 어떤 콘텐츠에 반응할까?</p><small>예측 · 순위 매기기</small></article><article><span class="example-number">02</span><h3>음성 자막</h3><p>소리를 어떤 글자로 옮길까?</p><small>인식 · 변환</small></article><article><span class="example-number">03</span><h3>사진 만들기</h3><p>설명에 어울리는 장면은 어떤 모습일까?</p><small>생성</small></article><article><span class="example-number">04</span><h3>이동 로봇</h3><p>다음에는 어느 방향으로 움직일까?</p><small>의사결정 · 제어</small></article></div><p class="lead" style="margin-top:24px">공통 질문: 입력은 무엇이고, 출력은 무엇일까요?</p>`,`예시는 AI를 사용할 수 있는 기능이지 모든 제품이 반드시 AI를 쓴다는 뜻은 아닙니다. 학생이 오늘 쓴 기능 하나를 골라 입력과 출력을 말하게 하세요. AI와 모든 자동화를 같은 말로 쓰지 않는 연습입니다.`);
insertAfter('learning','xor','02 / 한 개의 선이 가진 한계','한 줄로 나눌 수<br>없는 문제도 있습니다.',split(`<p class="lead">둘 중 하나만 켜져 있으면 켜진다.<br>둘 다 같으면 꺼진다.</p><p>XOR는 하나의 직선 경계로 구분할 수 없는 고전적인 예입니다. 중간 계산을 조합하면 표현할 수 있습니다.</p>${source('history','IBM · 신경망 역사의 맥락')}`,lab('LAB 09 / XOR와 중간 계산',`<div class="row"><label><input id="xor-a" type="checkbox">입력 A</label><label><input id="xor-b" type="checkbox">입력 B</label></div><div id="xor-board" class="xor-board"></div><label><input id="xor-hidden" type="checkbox">중간 계산 펼치기</label><div id="xor-result" class="output" aria-live="polite"></div><p class="small">손으로 정한 논리 연산입니다. 신경망을 학습시키는 실험은 아닙니다.</p>`)),`4개 입력 위치를 확인합니다. 대각선으로 같은 결과인 두 집합을 직선 하나로 분리할 수 있는지 질문하세요. 중간 단계 (A OR B) AND NOT(A AND B)가 XOR를 구현합니다. 깊을수록 무조건 좋다는 뜻은 아닙니다.`);
insertAfter('xor','fit','02 / 배움과 암기의 차이','외운 문제는 잘 풀고,<br>새 문제는 틀린다면?',split(`<p class="lead">훈련 예시를 완벽하게 맞추는 것이<br>항상 목표는 아닙니다.</p><p>과적합은 훈련 데이터에는 잘 맞지만 처음 보는 데이터에는 잘 맞지 않는 상태입니다.</p>${source('overfit','Google · Overfitting')}`,lab('LAB 10 / 곡선의 복잡도 비교',`<svg id="fit-plot" class="plot" viewBox="0 0 500 260" role="img" aria-label="가상 훈련 데이터와 예측 곡선"></svg><label>모델 방식<select id="fit-mode"><option value="constant">단순한 평균</option><option value="linear" selected>직선으로 학습</option><option value="memorize">예시를 모두 통과하는 고차 곡선</option></select></label><label style="margin-top:14px"><input id="fit-test" type="checkbox">숨겨둔 시험 데이터 보기</label><div id="fit-result" class="output" aria-live="polite"></div><p class="small">가상 숫자 데이터에 실제 평균·최소제곱 직선·다항 보간을 적용합니다. 복잡한 모델이 불리한 예시를 선택한 실험입니다.</p>`)),`고차 곡선의 훈련 오차가 0에 가까운 것을 본 뒤 시험 데이터를 공개합니다. 모델이 무조건 단순해야 한다는 결론도 피하세요. 데이터에 맞는 복잡도와 독립적인 평가가 필요합니다. 시험 점수로 반복 조정하면 시험 데이터에도 맞춰질 수 있습니다.`);
insertAfter('fit','data','02 / 무엇을 가르쳤을까','데이터가 빠뜨린 세상은<br>모델도 놓칠 수 있습니다.',split(`<p class="lead">전체 정답률 90%.<br>그 말만으로 충분할까요?</p><p>어떤 환경에서 틀렸는지 나누어 봐야 합니다. 큰 집단의 좋은 성능이 작은 집단의 실패를 가릴 수 있습니다.</p>`,lab('LAB 11 / 평균 뒤에 숨은 오류',`<label>시험 사진 중 낮 사진의 비중 <output id="day-out"></output><input id="day-share" type="range" min="0" max="100" value="90"></label><div class="bars"><div class="bar"><span>낮 사진</span><div class="track"><div class="fill" style="width:95%"></div></div><span>95%</span></div><div class="bar"><span>밤 사진</span><div class="track"><div class="fill" style="width:45%"></div></div><span>45%</span></div></div><div id="data-result" class="output" aria-live="polite"></div><p class="small">집단별 정확도는 고정한 가상 값입니다. 비중을 바꾸면 가중 평균이 바뀝니다. 실제 서비스 측정값은 아닙니다.</p>`)),`낮 90%, 밤 10%일 때 전체 90%입니다. 밤 비중을 늘려보세요. 모델이 변하지 않았는데 전체 지표가 달라집니다. “우리 학교 모든 학생에게도 잘 작동할까?”로 연결하고, 누구의 사례가 빠졌는지 묻습니다.`);
insertAfter('reinforcement','reward','02 / 목표를 잘 정하는 일','우리가 시킨 일과<br>원했던 일은 같을까요?',split(`<p class="lead">추천 AI에게 ‘클릭 수’만<br>최대한 늘리라고 한다면?</p><p>측정하기 쉬운 숫자가 진짜 목적을 온전히 나타내지는 않을 수 있습니다.</p>`,lab('LAB 12 / 추천 기준 바꾸기',`<label>추천에서 학습 도움을 반영하는 비중 <output id="reward-out"></output><input type="range" id="reward-mix" min="0" max="100" value="0"></label><div id="reward-ranking" class="stack"></div><p class="small">가상의 콘텐츠 3개에 클릭 기대 점수와 학습 도움 점수를 정했습니다. 실제 추천 모델이나 사용자 데이터는 아닙니다.</p>`)),`클릭 점수만 보면 자극적인 제목이, 학습 비중을 높이면 설명 영상이 위로 오르게 설계했습니다. 실제 학습 도움은 측정 자체가 어렵습니다. 누가 목표를 정하며 다른 중요한 가치가 누락되지 않았는지 토론합니다.`);
insertAfter('attention','diffusion','02 / AI의 시간 · 2020 → 이미지 생성','문장만이 아니라,<br>이미지도 만들어내다.',split(`<p class="lead">노이즈를 줄이는 방법을 배우면,<br>잡음에서 새로운 샘플을 만들 수 있습니다.</p><p>확산 모델은 이미지에 잡음을 넣는 과정과 이를 되돌리는 학습을 활용합니다. 2020년 DDPM은 대표적인 이정표입니다.</p>${source('diffusion','Ho 외 · Denoising Diffusion Probabilistic Models')}`,lab('LAB 13 / 신호와 잡음',`<svg id="noise-plot" class="plot" viewBox="0 0 500 220" role="img" aria-label="노이즈 수준에 따른 숫자 신호 변화"></svg><label>잡음의 양 <output id="noise-out"></output><input id="noise-level" type="range" min="0" max="100" value="100"></label><button id="noise-step">잡음 한 단계 줄이기</button><p class="small">원래 신호를 알고 혼합 비율을 바꾸는 설명용 비유입니다. 실제 확산 모델은 신경망으로 잡음 등을 예측하며 원본을 단순히 드러내는 방식이 아닙니다.</p>`)),`곡선은 숫자 신호여서 이미지 생성의 정확한 내부 시각화가 아닙니다. 잡음과 신호의 관계를 이해하는 데만 사용하세요. 실제 샘플링은 특정 원본이 숨겨져 있는 것을 복원하는 과정이 아닙니다. 기존 Transformer 설명과 이어서, 생성 AI 안에도 서로 다른 설계가 있음을 짚습니다.`);
insertAfter('generation','prompt','02 / 잘 묻는 연습','“발표 만들어줘”를<br>조금 더 분명하게.',split(`<p class="lead">대상, 목적, 제약, 확인 기준.<br>요청이 구체적이면 검토도 쉬워집니다.</p><p>길게 쓰는 것보다, 중요한 조건을<br>빠뜨리지 않는 것이 먼저입니다.</p>`,lab('PROMPT WORKSHOP / 요청 조립하기',`<label><input class="prompt-part" type="checkbox" value="대상은 AI를 처음 배우는 고등학생이다.">누구에게: AI를 처음 배우는 고등학생</label><label><input class="prompt-part" type="checkbox" value="목적은 과적합을 자기 말로 설명할 수 있게 하는 것이다.">목적: 과적합을 설명하게 만들기</label><label><input class="prompt-part" type="checkbox" value="3분 분량, 수식 없이, 학교생활 비유 한 개로 설명해줘.">제약: 3분·수식 없이·비유 하나</label><label><input class="prompt-part" type="checkbox" value="비유의 한계와 확인 가능한 출처를 덧붙여줘.">확인: 비유의 한계와 출처</label><div id="prompt-result" class="output" aria-live="polite">발표 만들어줘.</div><p class="small">선택한 요청 문장을 조립합니다. AI에 전송하지 않습니다. 출처를 요청해도 링크와 내용은 직접 확인해야 합니다.</p>`)),`AI 결과 대신 요청 자체를 비교하는 실험입니다. 학생에게 한 가지 조건을 추가하게 합니다. “전문가처럼 해줘”라는 역할 지정보다 실제 대상과 성공 기준을 제시하는 연습을 강조하세요.`);
insertAfter('prompt','rag','02 / 근거를 가져오는 AI','말을 잘하는 것과<br>근거가 있는 것은 다릅니다.',split(`<p class="lead">RAG: 관련 자료를 검색해<br>답변의 참고 문맥으로 사용하기.</p><p>모델의 기억에만 기대지 않고 문서를 참고하게 할 수 있습니다. 그래도 자료의 날짜와 정확성을 확인해야 합니다.</p>${source('rag','Lewis 외 · Retrieval-Augmented Generation')}`,lab('LAB 14 / 가상 동아리 공지 찾기',`<p>질문: “과학 동아리 모임은 언제야?”</p><label>참고 문서<select id="rag-doc"><option value="none">참고 문서 없음</option><option value="old">지난 공지 · 월요일 16시</option><option value="new">수정 공지 · 화요일 17시</option></select></label><button id="rag-ask" style="margin-top:16px">근거와 답 확인</button><div id="rag-result" class="output" aria-live="polite">참고할 자료를 골라보세요.</div><p class="small">미리 작성한 가상 공지와 답변을 연결합니다. 실제 검색기나 LLM을 호출하지 않습니다. 한솔고등학교의 실제 일정이 아닙니다.</p>`)),`문서 없음 → 오래된 문서 → 최신 문서로 바꿔봅니다. 출처가 달렸다는 사실만으로 최신의 올바른 답이라고 할 수 있을까요? 질문과 관련 있는지, 신뢰할 만한 원문인지, 날짜가 맞는지 모두 필요합니다.`);
insertAfter('scenarios','school','03 / 학교에서 만날 선택','편리함 앞에서도,<br>내 기준은 필요합니다.',`<div class="row" id="school-cases"><button data-case="assignment">수행평가 초안</button><button data-case="photo">친구 사진</button><button data-case="source">그럴듯한 출처</button></div><div class="case-stage"><p id="school-situation" class="lead"></p><button id="school-reveal">함께 생각할 기준 보기</button><div id="school-answer" class="output" aria-live="polite"></div></div><p class="small">학교의 실제 과제 규칙과 당사자의 의사를 먼저 확인하는 토론입니다.</p>`,`정답 맞히기보다는 이유를 이야기하게 하세요. AI 이용 여부 자체보다 학습 목적, 동의, 출처, 책임이 중요합니다. 사례 중 하나만 1분 토론하고 나머지는 수업 뒤 읽을 수 있습니다.`);
insertAfter('skills','portfolio','04 / 실력을 보여주는 증거','완성 화면 뒤에<br>내 생각을 남겨보세요.',`<div class="example-grid"><article><span class="example-number">01</span><h3>문제</h3><p>동아리 공지가 여러 곳에 흩어져 있다.</p></article><article><span class="example-number">02</span><h3>시도</h3><p>익명화한 예시 공지로 일정표 초안을 만든다.</p></article><article><span class="example-number">03</span><h3>검증</h3><p>날짜·장소를 원문과 하나씩 대조한다.</p></article><article><span class="example-number">04</span><h3>회고</h3><p>틀린 날짜 하나를 고치고 다음에 확인할 규칙을 적는다.</p></article></div><p class="lead" style="margin-top:25px">“AI로 만들었어요” 다음에,<br>“저는 이것을 판단하고 고쳤어요.”</p>`,`학생에게 보여줄 가상의 프로젝트 기록입니다. 실제 성과나 사용자 수를 지어낸 사례가 아닙니다. 결과물과 함께 본인의 결정, AI 도움의 범위, 확인한 오류를 남기면 학습 과정이 보입니다.`);
insertAfter('nextweek','horizon','04 / 정해지지 않은 다음','너의 경로는<br>아직 쓰이는 중입니다.',`<figure class="scene"><img src="assets/future.png" alt="푸른 저녁의 길을 함께 걸으며 먼 풍경을 바라보는 학생들을 표현한 생성 이미지" width="1536" height="1024" loading="lazy"><figcaption>미래를 함께 탐색하는 학생들을 표현한 생성 이미지 · 실제 학교나 학생의 사진이 아닙니다.</figcaption></figure><p class="lead">한 번에 나를 정의하지 않아도 됩니다.<br>해보고, 배우고, 방향을 다시 고르면 됩니다.</p>`,`마무리 전 30초 정적을 두세요. 앞 장에서 적은 실천을 한 번 더 읽게 합니다. 이미지는 특정 학생이나 학교를 묘사한 기록 사진이 아닙니다.`);
// Split the same 100 minutes into smaller teaching beats.
CNN.addSlides(insertAfter,split,lab);
VisualExamples.addSlides(sections,insertAfter,split,lab);
TransformerExamples.addSlides(sections,insertAfter,split,lab);
const timing={intro:2,opening:2,beginning:2,story:3,turning:3,choices:2,compass:4,everyday:2,rules:3,learning:3,xor:3,fit:2,data:2,winter:2,deep:2,'cnn-filter':3,'cnn-pooling':3,'cnn-flow':2,reinforcement:2,'alphago-search':2,reward:2,'transformer-tokens':1,attention:2,'transformer-qkv':2,'transformer-mask':1,diffusion:1,'diffusion-generation':2,generation:3,prompt:1,rag:2,agents:2,pause:5,future:4,jobs:3,scenarios:3,school:3,skills:3,portfolio:2,nextweek:3,horizon:1,closing:5};
let minute=0;sections.forEach(s=>{if(timing[s.id]){let n=timing[s.id];s.time=`${String(minute).padStart(2,'0')}–${String(minute+n).padStart(2,'0')}분 · ${n}분`;minute+=n;}});
const revisedNotes={
intro:'제목을 보여준 뒤 AI 사용 경험과 진로 걱정을 손들기로 물어보세요. 지역을 가능성의 한계로 규정하지 않도록 제목의 뜻을 설명합니다.',
opening:'선택을 하나 고르고 옆 사람에게 이유를 말하게 하세요. 이 선택은 학급 투표로 집계되지 않습니다. 오늘은 평생의 직업 대신 다음 실험을 고르는 시간입니다.',
story:'회사 소개는 짧게 하고 검색, 플랫폼, 광고, 여행에서 실제 어떤 문제를 풀었는지 설명하세요. 경력에서 입사 동기나 감정을 추정하지 않았습니다.',
turning:'실제 이야기 세 장면을 준비하세요: 컴퓨터를 만난 계기, 막막했던 경험, 진로를 바꾼 이유. 상황 → 선택 → 대가 → 배운 점으로 들려주세요. 확인되지 않은 일화는 작성하지 않았습니다.',
compass:'관심과 불편을 적고 작은 실험을 옆 사람에게 설명해보세요. 결과는 입력을 조합한 활동 안내이며 AI 생성이 아닙니다. 건강·관계·시간도 진로 선택의 기준임을 덧붙이세요.',
rules:'무료 급식, 공짜 쿠폰을 순서대로 넣고 오탐과 놓치는 예시를 비교하세요. 이 실험은 학습하지 않습니다. 규칙 기반과 신경망 연구는 시기상 겹칩니다.',
learning:'경계를 조절한 뒤 학습을 반복하고 편향된 데이터로 바꿔보세요. 작은 경계 후보 탐색 알고리즘이며 퍼셉트론 업데이트 자체는 아닙니다. 훈련 정답 수와 새 시험 정답 수를 구분합니다.',
winter:'탐색 깊이를 4에서 8로 바꾸면 계산량이 두 배가 되는지 먼저 물어보세요. 실제 체스 탐색은 가지치기와 평가를 활용합니다. AI의 겨울에도 연구는 이어졌습니다.',
deep:'세로선을 그려 가로·세로 필터를 비교하세요. 작은 창에서 값을 곱하고 더해 특징을 찾습니다. 실제 CNN은 필터도 학습하지만 여기서는 고정 필터의 반응만 봅니다.',
reinforcement:'학습 전 경로 → 200번 연습 → 배운 경로를 비교하세요. Q-learning 격자 실험이며 AlphaGo 자체의 재현은 아닙니다. 탐험과 배운 전략의 사용을 구분합니다.',
attention:'문장을 바꾸고 단어를 눌러 문맥의 연결을 확인하세요. 표시한 수치는 수작업 예시입니다. 실제 attention은 입력에서 가중치를 계산하며, 이 그림이 이해나 의식을 증명하지 않습니다.',
generation:'온도를 바꾸고 여러 번 단어를 뽑아보세요. 확률은 softmax(log(p)/T)로 바뀌지만 지식이 늘어나는 것은 아닙니다. 낮은 온도도 사실성을 보장하지 않습니다.',
agents:'오래된 가격이 켜진 상태에서 단계별로 진행하세요. 가상의 계획·도구·검사·재시도·사람 확인입니다. 실시간 검색이나 예약·결제는 하지 않습니다.',
pause:'5분 휴식. 타이머를 켜고 화면 밖을 보게 하세요. 돌아오면 규칙, 학습, 도구 사용의 차이를 짧게 회상합니다.',
future:'각 전망을 설명한 뒤 자신의 판단과 판단을 바꿀 증거를 말하게 합니다. 두 글의 요약이며 직접 인용이 아닙니다. 고용 규모·도입 속도·새 수요·정책의 가정을 비교합니다.',
jobs:'한 직업을 고르고 업무를 AI 초안·협업·사람 중심으로 나누세요. 서로 다른 분류의 이유를 듣습니다. 통계적 자동화 확률이나 영원히 안전한 직업 목록이 아닙니다.',
scenarios:'세 시나리오를 읽고 초급 업무가 바뀌면 경험을 어디에서 쌓을 수 있을지 이야기하세요. 변화의 시점과 규모는 불확실하며 기회의 문제를 개인의 노력만으로 설명하지 않습니다.',
skills:'AI 초안을 그대로 제출하는 경우와 내 말로 설명하고 검증하는 경우를 비교하세요. 학습 목적과 학교 규칙, 개인정보, 출처를 구체적인 행동으로 연결합니다.',
nextweek:'해볼 일과 성공의 증거를 적고 짝에게 설명하세요. AI 접근이 어려우면 종이 초안으로 시작해도 됩니다. 틀린 점 하나를 발견하는 것도 좋은 학습 증거입니다.',
closing:'질문을 받고 마지막에는 오늘 고른 실험을 떠올리게 하세요. 안전을 보장하는 직업을 단정하기보다 관심 분야의 실제 업무와 다음 학습을 함께 생각합니다.'
};
sections.forEach(s=>{if(s.id!=='sources')s.note=`배정 ${timing[s.id]}분. `+(revisedNotes[s.id]||s.note);});
const appendix=sections.find(s=>s.id==='sources');appendix.body+=`<div class="sources" style="margin-top:24px"><div>${source('overfit','추가 · 과적합과 일반화')}</div><div>${source('diffusion','추가 · 확산 모델')}</div><div>${source('rag','추가 · 검색 증강 생성')}</div></div>`;

const chapterImage=(path,alt,caption)=>`<figure class="chapter-art"><img src="assets/${path}" alt="${alt}" width="1536" height="1024" loading="lazy"><figcaption>${caption} · 생성 이미지</figcaption></figure>`;
sections.find(s=>s.id==='everyday').body+=chapterImage('learning-daylight.png','햇빛이 드는 책상에 놓인 노트와 패턴을 이루는 블록','호기심과 패턴 학습을 표현한 장면');
sections.find(s=>s.id==='portfolio').body+=chapterImage('students-daylight.png','밝은 도서관에서 종이 시제품을 함께 검토하는 세 학생','함께 만들고 검토하는 과정을 표현한 가상 장면');
const companyMarks=[['넥슨','nexon.png','nexon','https://brand.nexon.com/ko/ci-brand-guidelines/primary-identity'],['Google','google.webp','google','https://about.google/brand-resource-center/products-and-services/'],['Moloco','moloco.jpg','moloco','https://www.moloco.com/'],['야놀자 · NEXT','yanolja-orange.jpg','yanolja','https://www.yanoljagroup.com/ko/brand_center']];
const careerSlide=sections.find(s=>s.id==='story');
companyMarks.forEach(([name,file,cls,url])=>{careerSlide.body=careerSlide.body.replace(`<article><strong>${name}</strong>`,`<article><a class="company-mark ${cls}" href="${url}" target="_blank" rel="noopener noreferrer" aria-label="${name} 공식 사이트"><img src="assets/logos/${file}" alt="${name} 로고" loading="lazy"></a><strong>${name}</strong>`);});
const schoolMark=`<div class="school-mark"><img src="assets/logos/hansol.png" width="64" height="64" alt="분당 한솔고등학교 교표"><div><strong>한솔고등학교</strong><span>경기도 성남시 분당구 · 진로 멘토링</span></div></div>`;
sections.find(s=>s.id==='intro').body=schoolMark+sections.find(s=>s.id==='intro').body;
sections.find(s=>s.id==='closing').body+=schoolMark;
sections.find(s=>s.id==='sources').body+=`<div class="logo-sources"><p class="small">로고 출처</p><a href="https://brand.nexon.com/ko/ci-brand-guidelines/primary-identity" target="_blank" rel="noopener noreferrer">넥슨 브랜드 가이드</a><a href="https://about.google/brand-resource-center/products-and-services/" target="_blank" rel="noopener noreferrer">Google 브랜드 자료</a><a href="https://www.prnewswire.com/apac/news-releases/moloco-strengthens-asia-pacific-footprint-with-key-leadership-hires-302323602.html" target="_blank" rel="noopener noreferrer">Moloco 공식 보도자료</a><a href="https://www.yanoljagroup.com/ko/brand_center" target="_blank" rel="noopener noreferrer">야놀자 브랜드 센터</a><a href="https://www.goesn.kr/sngg/na/ntt/selectNttInfo.do?bbsId=19853&mi=25662&nttSn=1880459" target="_blank" rel="noopener noreferrer">성남교육지원청 · 한솔고 학교 소개 자료</a></div>`;
const publicLectureUrl='https://jay-jang.github.io/accidental-ai-hansol/';
const openingSlide=sections.find(s=>s.id==='opening');
const agendaAt=openingSlide.body.indexOf('<div class="agenda">');
const openingQuestion=openingSlide.body.slice(0,agendaAt);
const openingAgenda=openingSlide.body.slice(agendaAt);
openingSlide.body=`<div class="join-layout"><div>${openingQuestion}</div><figure class="join-qr"><h3>내 휴대폰으로 실험하기</h3><a href="${publicLectureUrl}" target="_blank" rel="noopener noreferrer" aria-label="어쩌다 AI 강의 페이지 열기"><img src="assets/github-pages-qr.png" width="656" height="656" alt="GitHub Pages 강의 페이지 접속 QR 코드"></a><figcaption>카메라로 QR 코드를 비춰주세요.<br><a class="join-url" href="${publicLectureUrl}" target="_blank" rel="noopener noreferrer">jay-jang.github.io/<wbr>accidental-ai-hansol/</a></figcaption><a class="qr-download" href="assets/github-pages-qr.png" download="hansol-ai-lecture-qr.png">QR 이미지 저장 ↓</a></figure></div>${openingAgenda}`;
openingSlide.note='배정 2분. 먼저 QR 코드를 비춰 각자 강의 페이지를 열게 하세요. 로그인이 필요하지 않습니다. 접속 후 현재의 진로 생각을 하나 골라보게 합니다. 선택은 각자의 화면에서만 바뀌며 학급 응답을 수집하지 않습니다.';
sections.find(s=>s.id==='sources').body+=`<div class="source">야놀자 주황색 로고 원본: <a href="https://www.yanoljagroup.com/en/press_release/view?id=1534" target="_blank" rel="noopener noreferrer">야놀자 공식 보도자료 · 2026년 3월</a></div>`;
const researchPhotos=[
  {id:'winter',file:'deep-blue-museum.jpg',alt:'컴퓨터 역사박물관에 전시된 딥 블루와 같은 계열의 IBM 컴퓨터',caption:'딥 블루와 같은 계열의 IBM 컴퓨터 · 박물관 전시',credit:'James the photographer / CC BY 2.0',url:'https://commons.wikimedia.org/wiki/File:Deep_Blue.jpg'},
  {id:'reinforcement',file:'alphago-match.jpg',alt:'바둑판을 바라보며 생각하는 이세돌',caption:'2016 · AlphaGo와 대국 중인 이세돌',credit:'Google DeepMind',url:'https://deepmind.google/research/alphago/'}
];
for(const photo of researchPhotos){
  const slide=sections.find(s=>s.id===photo.id);
  const figure=`<figure class="research-photo"><a href="${photo.url}" target="_blank" rel="noopener noreferrer"><img src="assets/research/${photo.file}" alt="${photo.alt}" loading="lazy"></a><figcaption>${photo.caption} · <a href="${photo.url}" target="_blank" rel="noopener noreferrer">사진: ${photo.credit} ↗</a></figcaption></figure>`;
  slide.body=slide.body.replace('<div class="split"><div>','<div class="split"><div>'+figure);
}
const personHeading=(file,name,detail,credit,url,license='')=>`<figure class="person-heading"><img src="assets/people/${file}.jpg" alt="${name} 사진" width="112" height="112" loading="lazy"><figcaption><strong>${name}</strong><span>${detail}</span><a class="portrait-credit" href="${url}" target="_blank" rel="noopener noreferrer">사진: ${credit} ↗</a>${license?`<a class="portrait-credit" href="https://creativecommons.org/licenses/by/2.0/" target="_blank" rel="noopener noreferrer">CC BY 2.0 · 원본은 Commons에서 크롭</a>`:''}</figcaption></figure>`;
const ngPortrait=personHeading('andrew-ng','Andrew Ng · 앤드루 응','전망 글 · 2026.02.20','Steve Jurvetson · 2017','https://commons.wikimedia.org/wiki/File:Andrew_Ng_WSJ_(2).jpg',true);
const gatesPortrait=personHeading('bill-gates','Bill Gates · 빌 게이츠','전망 글 · 2026년','Christopher Smith / HHS · 2018 · Public domain','https://commons.wikimedia.org/wiki/File:Bill_Gates_2018.jpg');
const turingPortrait=personHeading('alan-turing','Alan Turing · 앨런 튜링','기계의 지능을 질문하다','Elliott & Fry · 1951 · Public domain','https://commons.wikimedia.org/wiki/File:Alan_Turing_(1951).jpg');
const futurePortraitSlide=sections.find(s=>s.id==='future');
futurePortraitSlide.body=futurePortraitSlide.body.replace('<div class="eyebrow">ANDREW NG <span>2026.02.20</span></div>',ngPortrait).replace('<div class="eyebrow">BILL GATES <span>2026년 글 · 9월 7일 확인</span></div>',gatesPortrait);
const turingSlide=sections.find(s=>s.id==='rules');turingSlide.body=turingSlide.body.replace('<div class="split"><div>','<div class="split"><div>'+turingPortrait);
$('#main').innerHTML=sections.map((s,i)=>`<section id="${s.id}" class="${researchPhotos.some(p=>p.id===s.id)?'has-research-photo':''}"><div class="slide-content">${i?`<div class="eyebrow">${s.kicker}<span>${s.time}</span></div>`:''}${s.title?`<h2>${s.title}</h2>`:''}${s.body}</div><aside class="note"><strong>진행 노트 · ${s.time}</strong><br>${s.note}</aside></section>`).join('');
let current=0;const go=n=>{current=Math.max(0,Math.min(sections.length-1,n));$('#'+sections[current].id).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
$('#prev').onclick=()=>go(current-1);$('#next').onclick=()=>go(current+1);
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName)||e.altKey||e.ctrlKey||e.metaKey)return;if(['ArrowDown','PageDown','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();go(current+(['ArrowDown','PageDown'].includes(e.key)?1:-1));}});
let pending=false;window.addEventListener('scroll',()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{let best=0,dist=Infinity;$$('section').forEach((el,i)=>{const d=Math.abs(el.getBoundingClientRect().top);if(d<dist){dist=d;best=i;}});current=best;$('#position').textContent=`${String(best+1).padStart(2,'0')} / ${sections.length}`;$('#chapter').textContent=sections[best].kicker;$('#progress').style.width=((best+1)/sections.length*100)+'%';$('#prev').disabled=best===0;$('#next').disabled=best===sections.length-1;pending=false;});},{passive:true});
$('#notes-toggle').onclick=()=>{const on=document.body.classList.toggle('show-notes');$('#notes-toggle').setAttribute('aria-pressed',on);};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('#fullscreen').textContent='미지원';}};
$$('[data-thought]').forEach(b=>b.onclick=()=>{$$('[data-thought]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#opening-result').textContent=b.dataset.thought;});
$('#experiment').onclick=()=>{const a=$('#interest').value.trim(),b=$('#problem').value.trim();$('#experiment-result').textContent=a&&b?`${a}에 대한 관심으로 “${b}”를 겪는 한 사람을 만나보세요. 30분 안에 종이 초안을 만들고, 도움이 되는지 물어보세요.`:'관심 있는 것과 주변의 불편을 모두 적어주세요.';};
function rule(){let t=$('#rule-input').value;$('#rule-result').textContent=!t.trim()?'검사할 메시지를 입력하세요.':t.includes('무료')&&!($('#rule-extra').checked&&t.includes('급식'))?'광고로 분류했습니다.':'일반 메시지로 분류했습니다.';}$('#rule-input').oninput=rule;$('#rule-extra').onchange=rule;rule();
let biased=false;const normal=[[24,0],[34,0],[41,0],[48,0],[60,1],[69,1],[78,1],[88,1]],skew=[[24,0],[28,0],[32,0],[36,0],[40,1],[44,1]],test=[[38,0],[46,0],[53,0],[58,1],[67,1],[82,1]];
const error=(data,t)=>data.filter(([x,y])=>+(x>=t)!==y).length;
function learning(){const t=+$('#threshold').value,data=biased?skew:normal;$('#threshold-text').textContent=t;let out='<text x="16" y="24" fill="#526675" font-size="13">훈련 예시 · 가상 무게</text>';for(let y of [65,127])out+=`<line x1="40" y1="${y}" x2="460" y2="${y}" stroke="#18384c35"/>`;for(const [set,y]of [[data,65],[test,127]])for(const [x,c]of set){let cx=40+(x-20)*6;out+=c?`<path d="M${cx} ${y-7}l7 7-7 7-7-7Z" fill="#997349"/>`:`<circle cx="${cx}" cy="${y}" r="6" fill="#256783"/>`;}out+=`<line x1="${40+(t-20)*6}" y1="36" x2="${40+(t-20)*6}" y2="148" stroke="#213e52" stroke-dasharray="5 4"/><text x="16" y="108" fill="#526675" font-size="13">새 시험 예시</text>`;$('#learn-plot').innerHTML=out;$('#learn-result').textContent=`훈련 ${data.length-error(data,t)}/${data.length}개 정답 · 새 시험 ${test.length-error(test,t)}/${test.length}개 정답`;$('#bias').textContent=biased?'전체 데이터로 돌아가기':'편향된 데이터 보기';}
$('#threshold').oninput=learning;$('#train').onclick=()=>{let data=biased?skew:normal,best=20,min=Infinity;for(let t=20;t<=90;t++){let e=error(data,t);if(e<min){min=e;best=t;}}let now=+$('#threshold').value;$('#threshold').value=now+Math.sign(best-now)*Math.min(5,Math.abs(best-now));learning();};$('#bias').onclick=()=>{biased=!biased;learning();};$('#learn-reset').onclick=()=>{biased=false;$('#threshold').value=30;learning();};learning();
function searching(){let b=+$('#branch').value,d=+$('#depth').value;$('#branch-out').textContent=b;$('#depth-out').textContent=d;$('#search-result').textContent=`${(b**d).toLocaleString('ko-KR')}개의 마지막 선택`;};$('#branch').oninput=searching;$('#depth').oninput=searching;searching();
let pixels=[];function pixelDraw(){let kernel=$('#filter').value==='edge'?[-1,0,1,-1,0,1,-1,0,1]:[-1,-1,-1,0,0,0,1,1,1],scores=[];for(let y=0;y<4;y++)for(let x=0;x<4;x++){let n=0;for(let j=0;j<3;j++)for(let i=0;i<3;i++)n+=pixels[(y+j)*6+x+i]*kernel[j*3+i];scores.push(Math.abs(n));}$('#pixels').innerHTML=pixels.map((v,i)=>`<button class="cell" data-pixel="${i}" aria-label="${Math.floor(i/6)+1}행 ${i%6+1}열" aria-pressed="${!!v}" style="background:${v?'#3f829d':'#e4edf1'}"></button>`).join('');$$('[data-pixel]').forEach(b=>b.onclick=()=>{pixels[+b.dataset.pixel]=1-pixels[+b.dataset.pixel];pixelDraw();});$('#filter-result').textContent=`경계 반응 합계 ${scores.reduce((a,b)=>a+b,0)} · 최대 반응 ${Math.max(...scores)}`;};function pixelReset(){pixels=Array.from({length:36},(_,i)=>+(i%6>2));pixelDraw();}$('#pixel-reset').onclick=pixelReset;$('#pixel-clear').onclick=()=>{pixels=Array(36).fill(0);pixelDraw();};$('#filter').onchange=pixelDraw;pixelReset();
let Q=Array.from({length:16},()=>[0,0,0,0]),episodes=0;let seed=47;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}function move(s,a){let x=s%4,y=Math.floor(s/4);if(a===0)y=Math.max(0,y-1);if(a===1)x=Math.min(3,x+1);if(a===2)y=Math.min(3,y+1);if(a===3)x=Math.max(0,x-1);return y*4+x;}function bestAction(s){return Q[s].indexOf(Math.max(...Q[s]));}function rlDraw(path=[]){$('#rl-grid').innerHTML=Array.from({length:16},(_,i)=>`<div class="cell" style="display:grid;place-items:center;border:1px solid #18384c26;background:${path.includes(i)?'#bfdce7':'#edf3f6'}">${i===0?'S':i===15?'G':i===6||i===10?'×':path.includes(i)?'●':'·'}</div>`).join('');}$('#rl-train').onclick=()=>{for(let e=0;e<200;e++){let s=0;for(let k=0;k<70;k++){let a=rand()<.25?Math.floor(rand()*4):bestAction(s),n=move(s,a),end=n===15||n===6||n===10,r=n===15?20:n===6||n===10?-15:-1;Q[s][a]+=.2*(r+(end?0:.9*Math.max(...Q[n]))-Q[s][a]);s=n;if(end)break;}}episodes+=200;$('#rl-result').textContent=`${episodes}번 연습했습니다. 배운 경로를 확인해보세요.`;rlDraw();};$('#rl-run').onclick=()=>{let s=0,path=[0],score=0;for(let k=0;k<24;k++){s=move(s,bestAction(s));path.push(s);score+=s===15?20:s===6||s===10?-15:-1;if([15,6,10].includes(s))break;}rlDraw(path);$('#rl-result').textContent=`${s===15?'목표 도착':s===6||s===10?'함정에 도착':'24번 이동 후 아직 도착하지 못함'} · 보상 ${score}`;};$('#rl-reset').onclick=()=>{Q=Array.from({length:16},()=>[0,0,0,0]);episodes=0;seed=47;rlDraw();$('#rl-result').textContent='초기화했습니다. 연습 전 경로도 확인해보세요.';};rlDraw();
function attention(selected=1){let words=$('#context').value==='money'?['나는','은행에서','돈을','찾았다']:['나는','은행나무','아래에서','쉬었다'];let weights=selected===1?[$('#context').value==='money'?8:6,12,$('#context').value==='money'?55:62,$('#context').value==='money'?25:20]:words.map((_,i)=>i===selected?55:15);$('#token-list').innerHTML=words.map((w,i)=>`<button data-token="${i}" aria-pressed="${i===selected}">${w}</button>`).join('');$('#attention-bars').innerHTML=words.map((w,i)=>bar(w,weights[i])).join('');$$('[data-token]').forEach(b=>b.onclick=()=>attention(+b.dataset.token));}function bar(w,v){return `<div class="bar"><span>${w}</span><div class="track"><div class="fill" style="width:${v}%"></div></div><span>${Math.round(v)}%</span></div>`;}$('#context').onchange=()=>attention();attention();
let probabilities=[];const words=['학교에','친구와','새롭게','우주로'];function temperature(){let t=+$('#temp').value,raw=[.55,.25,.15,.05].map(p=>p**(1/t)),sum=raw.reduce((a,b)=>a+b);probabilities=raw.map(p=>p/sum);$('#temp-out').textContent=t.toFixed(1);$('#prob-bars').innerHTML=words.map((w,i)=>bar(w,probabilities[i]*100)).join('');}$('#temp').oninput=temperature;$('#sample').onclick=()=>{let r=Math.random(),i=0;while(i<3&&r>probabilities[i]){r-=probabilities[i];i++;}$('#sample-word').textContent=words[i];};temperature();
let step=0,oldPrice=true;$('#agent-step').onclick=()=>{if(step===0){oldPrice=$('#agent-error').checked;$('#agent-error').disabled=true;}const flow=oldPrice?['계획: 교통비 + 입장료 + 식비를 조사합니다.','도구 응답: 교통 12,000원 + 입장 8,000원 + 식사 15,000원 = 35,000원.','검사: 입장료 자료가 오래됐습니다. 아직 계획을 확정할 수 없습니다.','재조회: 가상 최신 입장료 12,000원. 합계 39,000원으로 수정합니다.','사람 확인: 예산 안입니다. 날짜·운영 시간·이동 경로를 확인하고 승인해야 합니다.']:['계획: 교통비 + 입장료 + 식비를 조사합니다.','도구 응답: 교통 12,000원 + 입장 12,000원 + 식사 15,000원 = 39,000원.','검사: 자료 기준일과 합계를 확인했습니다. 예산 50,000원 이내입니다.','사람 확인: 날짜·운영 시간·이동 경로를 확인하고 승인해야 합니다.'];$('#agent-result').textContent=flow[step];step++;if(step>=flow.length){$('#agent-step').disabled=true;$('#agent-result').textContent+=' 실제 예약은 하지 않습니다.';}};$('#agent-reset').onclick=()=>{step=0;$('#agent-step').disabled=false;$('#agent-error').disabled=false;$('#agent-result').textContent='목표를 읽고 조건을 정리할 준비가 됐습니다.';};
let timer=null,remaining=300,end=0;function clock(){let t=timer?Math.max(0,Math.ceil((end-Date.now())/1000)):remaining;$('#break-clock').textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;if(timer&&t===0){clearInterval(timer);timer=null;remaining=0;$('#break-start').textContent='휴식 완료';}}$('#break-start').onclick=()=>{if(timer){remaining=Math.max(0,Math.ceil((end-Date.now())/1000));clearInterval(timer);timer=null;$('#break-start').textContent='계속';}else{if(!remaining)remaining=300;end=Date.now()+remaining*1000;timer=setInterval(clock,250);$('#break-start').textContent='일시정지';}clock();};$('#break-reset').onclick=()=>{clearInterval(timer);timer=null;remaining=300;$('#break-start').textContent='타이머 시작';clock();};
$$('[data-future]').forEach(b=>b.onclick=()=>{$$('[data-future]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#future-result').textContent=b.dataset.future;});
const jobs={teacher:['학습 자료 초안 만들기','학생의 오개념 파악하기','갈등 상황에서 학생과 대화하기','평가 기준을 정하고 결과 설명하기'],developer:['반복 코드 초안 만들기','요구사항의 모순 찾기','장애 원인 확인과 복구 판단','사용자와 해결할 문제 합의하기'],designer:['시안 여러 개 만들기','사용자 관찰과 인터뷰','접근성·문화적 맥락 검토','최종 의도와 선택 설명하기'],nurse:['안내문 초안 만들기','기록의 누락 점검하기','환자 상태 변화에 현장 대응하기','환자·보호자와 신뢰 형성하기']};function jobResult(){let selects=$$('#job-tasks select'),n=[0,0,0];selects.forEach(s=>n[+s.value]++);$('#job-result').textContent=`AI 초안 ${n[0]} · 협업 ${n[1]} · 사람 중심 ${n[2]} — 왜 그렇게 나눴나요?`;}function job(){let tasks=jobs[$('#job').value];$('#job-tasks').innerHTML=tasks.map((t,i)=>`<div class="task"><span>${t}</span><select aria-label="${t}의 역할">${['AI 초안','사람과 협업','사람 중심'].map((v,k)=>`<option value="${k}" ${k===Math.min(i,2)?'selected':''}>${v}</option>`).join('')}</select></div>`).join('');$$('#job-tasks select').forEach(s=>s.onchange=jobResult);jobResult();}$('#job').onchange=job;job();
$('#commit-btn').onclick=()=>{let a=$('#commitment').value.trim(),b=$('#evidence').value.trim();$('#commit-result').textContent=a&&b?`나는 이번 주에 ${a} 성공의 증거: ${b}`:'해볼 일과 확인할 증거를 하나씩 적어주세요.';};
$('#position').textContent=`01 / ${sections.length}`;

function careerWeights(){const a=+$('#weight-learn').value,b=+$('#weight-life').value;$('#weight-learn-out').textContent=a;$('#weight-life-out').textContent=b;$('#choice-result').textContent=a+b?`기회 A ${((9*a+4*b)/(a+b)).toFixed(1)}점 · 기회 B ${((5*a+8*b)/(a+b)).toFixed(1)}점 — 어떤 기준을 빠뜨렸나요?`:'중요도를 하나 이상 정해보세요.';}$('#weight-learn').oninput=careerWeights;$('#weight-life').oninput=careerWeights;careerWeights();
function xor(){const a=+$('#xor-a').checked,b=+$('#xor-b').checked;$('#xor-board').innerHTML=[[0,0],[0,1],[1,0],[1,1]].map(([x,y])=>`<div class="xor-point ${x===a&&y===b?'chosen':''}"><span>A ${x} · B ${y}</span><strong>${x^y?'켜짐 · 1':'꺼짐 · 0'}</strong></div>`).join('');$('#xor-result').textContent=$('#xor-hidden').checked?`OR: ${a|b} / AND: ${a&b} → ${a|b} AND NOT(${a&b}) = ${a^b}`:`현재 출력 ${a^b} · ${a===b?'두 입력이 같습니다.':'두 입력이 다릅니다.'}`;}['#xor-a','#xor-b','#xor-hidden'].forEach(s=>$(s).onchange=xor);xor();
const trainPoints=[[.06,.2],[.22,.42],[.42,.31],[.64,.69],[.84,.61],[.96,.84]],testPoints=[[.12,.28],[.32,.39],[.53,.54],[.74,.66],[.91,.77]];
function fitPredict(x,mode){if(mode==='constant')return trainPoints.reduce((s,p)=>s+p[1],0)/trainPoints.length;if(mode==='memorize')return trainPoints.reduce((sum,[xi,yi],i)=>sum+yi*trainPoints.reduce((p,[xj],j)=>i===j?p:p*(x-xj)/(xi-xj),1),0);const mx=trainPoints.reduce((s,p)=>s+p[0],0)/6,my=trainPoints.reduce((s,p)=>s+p[1],0)/6;let num=0,den=0;trainPoints.forEach(([a,b])=>{num+=(a-mx)*(b-my);den+=(a-mx)**2;});return my+num/den*(x-mx);}
function fitting(){const mode=$('#fit-mode').value,test=$('#fit-test').checked;let out='<defs><clipPath id="fit-clip"><rect x="30" y="15" width="450" height="205"/></clipPath></defs><path d="M30 15V220H480" fill="none" stroke="#18384c55"/>';const pt=(x,y)=>`${30+x*450},${220-y*200}`;out+='<g clip-path="url(#fit-clip)"><polyline fill="none" stroke="#997349" stroke-width="2" points="'+Array.from({length:101},(_,i)=>pt(i/100,fitPredict(i/100,mode))).join(' ')+'"/>';trainPoints.forEach(([x,y])=>out+=`<circle cx="${30+x*450}" cy="${220-y*200}" r="5" fill="#256783"/>`);if(test)testPoints.forEach(([x,y])=>out+=`<path d="M${30+x*450} ${215-y*200}l5 5-5 5-5-5Z" fill="#ac7126"/>`);out+='</g><text x="35" y="248" fill="#526675" font-size="13">● 훈련 예시　◆ 숨겨둔 시험 예시</text>';$('#fit-plot').innerHTML=out;const mse=data=>data.reduce((s,[x,y])=>s+(fitPredict(x,mode)-y)**2,0)/data.length;$('#fit-result').textContent=`훈련 오차 ${mse(trainPoints).toFixed(4)}${test?' · 시험 오차 '+mse(testPoints).toFixed(4):' · 시험 오차는 아직 숨겨져 있습니다.'}`;}$('#fit-mode').onchange=fitting;$('#fit-test').onchange=fitting;fitting();
function dataShare(){let d=+$('#day-share').value;$('#day-out').textContent=d+'%';$('#data-result').textContent=`전체 정확도 ${(d*.95+(100-d)*.45).toFixed(1)}% · 밤 사진 정확도는 여전히 45%`;}$('#day-share').oninput=dataShare;dataShare();
function rewardMix(){const v=+$('#reward-mix').value;$('#reward-out').textContent=v+'%';const items=[['자극적인 제목의 짧은 영상',95,20],['친절한 수학 개념 설명',55,95],['과학 실험 브이로그',75,70]].map(([name,click,learn])=>({name,click,learn,score:(click*(100-v)+learn*v)/100})).sort((a,b)=>b.score-a.score);$('#reward-ranking').innerHTML=items.map((it,i)=>`<div class="rank-item"><b>${i+1}</b><div>${it.name}<br><small>클릭 ${it.click} · 학습 ${it.learn}</small></div><span>${it.score.toFixed(1)}</span></div>`).join('');}$('#reward-mix').oninput=rewardMix;rewardMix();
$$('.prompt-part').forEach(b=>b.onchange=()=>{const parts=$$('.prompt-part').filter(b=>b.checked).map(b=>b.value);$('#prompt-result').textContent=parts.length?'과적합에 대한 발표를 만들어줘. '+parts.join(' '):'발표 만들어줘.';});
$('#rag-ask').onclick=()=>{const k=$('#rag-doc').value;$('#rag-result').textContent=k==='none'?'참고 문서가 없어 일정을 확인할 수 없습니다. 공지 원문이 필요합니다.':k==='old'?'지난 공지에 따르면 월요일 16시입니다. [근거: 지난 공지] 이 문서가 최신인지는 확인하지 못했습니다.':'수정 공지에 따르면 화요일 17시입니다. [근거: 수정 공지] 이전의 월요일 16시 일정이 변경됐습니다.';};$('#rag-doc').onchange=()=>{$('#rag-result').textContent='문서가 바뀌었습니다. 근거와 답을 다시 확인하세요.';};
const schoolCases={assignment:['AI가 수행평가 초안을 써줬다. 그대로 제출해도 될까?','학교와 과제의 허용 범위를 확인합니다. 내가 이해한 내용을 내 말로 쓰고, AI 도움의 범위를 밝힙니다.'],photo:['재미있는 이미지를 만들려고 친구 사진을 업로드하려 한다.','사진 속 사람의 동의를 먼저 구합니다. 어디로 전송되고 어떻게 쓰이는지 모른다면, 가상의 인물로 바꿔볼 수 있습니다.'],source:['AI가 근사한 논문 제목과 링크를 제시했다. 출처로 써도 될까?','링크를 직접 열고 저자·제목·날짜를 확인합니다. 그 문서가 내 주장까지 뒷받침하는지 해당 부분을 읽습니다.']};let schoolCurrent='assignment';function schoolCase(k){schoolCurrent=k;$('#school-situation').textContent=schoolCases[k][0];$('#school-answer').textContent='';$$('[data-case]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.case===k));}$$('[data-case]').forEach(b=>b.onclick=()=>schoolCase(b.dataset.case));$('#school-reveal').onclick=()=>{$('#school-answer').textContent=schoolCases[schoolCurrent][1];};schoolCase('assignment');

// Fit the classroom layout after fonts, images and interactive results change.
// Small screens and enlarged browser text retain natural, accessible scrolling.
const slideMedia=matchMedia('(min-width: 1100px) and (min-height: 650px)');
let fitFrame=0;
function fitSlides(){
  fitFrame=0;
  document.querySelectorAll('.slide-content').forEach(content=>{
    content.style.zoom='1';
    if(!slideMedia.matches)return;
    const section=content.parentElement, style=getComputedStyle(section);
    const available=window.innerHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom)-4;
    // Keep at least 83% of the enlarged type; never clip unusually long user input.
    const scale=Math.max(.83,Math.min(1,available/content.scrollHeight));
    content.style.zoom=String(scale);
  });
}
function queueSlideFit(){if(!fitFrame)fitFrame=requestAnimationFrame(fitSlides);}
window.addEventListener('resize',queueSlideFit,{passive:true});
document.addEventListener('fullscreenchange',queueSlideFit);
document.fonts.ready.then(queueSlideFit);
document.querySelectorAll('#main img').forEach(img=>img.addEventListener('load',queueSlideFit));
new MutationObserver(queueSlideFit).observe($('#main'),{childList:true,subtree:true,characterData:true});
$('#main').addEventListener('input',queueSlideFit);
queueSlideFit();

CNN.init();

VisualExamples.init();

TransformerExamples.init();
